services:
  app:
    volumes:
      - .:/app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8182"
    depends_on:
      - mongo
    environment:
      # Variables para conectar con la base de datos
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_EXPOSE_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
